service: schedule-hugo2
provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements: ## Role statements that give certain access permissions into aws, we can also specify per function of which access goes to which
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"
functions: ## Our functions
  get_schedule: ## Function name
    handler: handler.get_schedule ## Where the code lives
    events: ## HTTP route
      - http: 
          path: schedule ## The path
          method: get ## Type of request
  add_event:
    handler: handler.add_event
    events:
      - http: 
          path: add_event
          method: post