service: hugo-schedule

provider:
  name: aws
  runtime: nodejs10.x

functions:
  get_schedule:
    handler: handler.get_schedule
    events:
      - http: 
          path: schedule
          method: get

