service: hugo-schedule

provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*"

functions:
  get_schedule:
    #function name in handler file (where the code lives)
    handler: handler.get_schedule
    #http route where people can access the information
    events:
      - http:
          path: schedule
          #type of method
          method: get
  get_event:
    handler: handler.get_event
    events:
      - http: 
          path: get_event
          method: get
  add_event:
    handler: handler.add_event
    events:
      - http: 
          path: add_event
          method: post